### PR TITLE
Adobe Commerce / Magento to Zoho CRM - Customers

### LINKED ISSUE #167: Adobe Commerce / Magento to Zoho CRM - Customers

### PR DESCRIPTION
**Pull request by FrendsSarlinS**
Closes #167 

Checklist for review:
- [x] Process name is fine, uses normal casing and descriptive
  - [x] If applicable, the process name follows the naming convention "{source/format} to {destination/format} - {object}"
- [x] Process description is fine, uses normal casing, dots and is descriptive
  - [x] Element names use normal casing, no unneeded capital letters
- [x] Correct casing used for formats and terms, e.g. CSV, FTP, JSON, Avro
  - [x] Element names do not contain dots
  - [x] Comments / note element text are in good language and end with dots
- [x] Template parameters checked
  - [x] Parameter follows the CamelCase naming convention, abbreviations included, e.g. ConnectionString, BaseUrl, ApiKey
  - [x] Parameter descriptions are good and end with dots
  - [x] Sensitive parameters are marked as secrets
- [x] "Turn off logging" switch is on for any task that has sensitive data as output, e.g. tokens in the header.
- [x] Process end points like error throws and return statements have titles (double-click) and reasonable information.
  - [x] Results have good summaries, preferably with statistics of some sort like "processed X files"
  - [x] Errors have some error info, usually from task (e.g. some ErrorMessage property contains additional error info)
  - [x] Errors are pointed downwards from their respective source, e.g. an exclusive decision
- [x] Process is organised with groups (dashed boxes)
- [x] Straight lines are preferred where possible
- [x] Subprocesses are forbidden
- [x] Text mode is preferred over Expressions in expressions, e.g. instead of *$"This is {#var.error}"* use *This is {{#var.error}}*
- [x] Process metadata file is present and content is fine (version number and name)
- [x] Process export file is present (process.json)
- [x] Process description file is present (all sections filled in)
- [x] Process description has a SVG screenshot of the process
- [x] Template files are going to the correct folder
- [x] Markdown paragraphs are separated with two newlines, so there is a blank line inbetween two paragraphs
- [x] If some system is integrated using e.g. a HTTP task (meaning we do not use a native connector for the system), then the system should be mentioned in additional systems used in metadata.json
- [x] If the template is handling some sample JSON data - make sure that the sample data is included in the long description (just one-two elements is enough)
- [x] If the template is assuming that there is a database table ready for data insertion / updates - include the table structure in the long description as a `CREATE TABLE` scipt.

## Summary by CodeRabbit

- **New Features**
  - Introduced a new template for synchronizing customer data between Adobe Commerce (Magento) and Zoho CRM, enabling users to fetch, insert, or update customer information.
  - Added a metadata file to facilitate integration configuration and management.
  - Developed a process template for effectively managing customer data import/export, enhancing operational efficiency.

- **Documentation**
  - Enhanced documentation for the newly introduced integration templates, providing detailed descriptions of functionality and usage.

### CODE REVIEW

**Review by charlotta-frends — COMMENTED** [review]
Works as intended! Comments:
- I feel that it'd be more logical to have the Magento get request to be immediately after the Magento token task, and the Zoho token task after that :D e.g., if you encounter errors with Magento, then the process doesn't needlessly generate the Zoho token yet.
- The Zoho data store reference is connected to the Match email task, though it should be connected to the insert/update tasks.
- A count for inserted and updated contacts would be nice for the end result!

long description:
- A mention of the refresh token's required scope could be added in either prerequisites or implementation notes.
- I think the Zoho client ID & secret and the knowing the regional domain URLs could also be mentioned as prerequisites (in the other Zoho templates as well!)

**Comment by FrendsSarlinS** [comment]
Thanks for the review, process and the description files are now updated!

A note to the data store reference: I added the references to the insert and update tasks as well. Match email had the reference intentionally, since that's where we get the information from. I normally utilize the data store reference like once per system included in the template, because otherwise you would need it all the time for every task, which would be messy 😄

**Comment by charlotta-frends** [comment]
> A note to the data store reference: I added the references to the insert and update tasks as well. Match email had the reference intentionally, since that's where we get the information from. I normally utilize the data store reference like once per system included in the template, because otherwise you would need it all the time for every task, which would be messy 😄

I see 😄 commented that because I tend to put one that's connected to both insert and update in similar cases. It's fine by me either way!

Noticed with my template, the scope should have the ZohoCRM.modules.contacts.UPDATE too.

Otherwise everything's looking great! If you still add that one scope to the long description, then it's ready for merging!

**Comment by FrendsSarlinS** [comment]
> I see 😄 commented that because I tend to put one that's connected to both insert and update in similar cases. It's fine by me either way!

Matter of personal taste, I guess! 😄 For me it adds clutter.
The new commit with scope updated is now in!

**Review by charlotta-frends — APPROVED** [review]

**Pull request merged**
