### PR TITLE
HTTP data paging from Microsoft SQL database

### LINKED ISSUE #108: HTTP data paging from Microsoft SQL database
Implement paging from MicrosoftSQL database for HTTP trigger. The process should get information from the selected SQL database table and field(s), and display it in a HTTP response for easy referencing.

Parameters:
- table where the information is retrieved from,
- fields that are retrieved,
- items per page.

### PR DESCRIPTION
**Pull request by FrendsSarlinS**
Closes #108 

Checklist for review:
- [x] Process name is fine, uses normal casing and descriptive
- [x] Process description is fine, uses normal casing, dots and is descriptive
  - [x] Element names use normal casing, no unneeded capital letters.
- [x] Correct casing used for formats and terms, e.g. CSV, FTP, JSON, Avro
  - [x] Element names do not contain dots
  - [x] Comments / note element text are in good language and end with dots.
- [x] Template parameters checked
  - [x] Parameter descriptions are good and end with dots.
  - [x] Sensitive parameters are marked as secrets
- [x] "Turn off logging" switch is on for any task that has sensitive data as output
- [x] End "balls" like error throws and return statements have titles (double-click) and reasonable information.
  - [x] Results have good summaries, preferably with statistics of some sort like "processed X files"
  - [x] Errors have some error info, usually from task (e.g. some ErrorMessage property contains additional error info)
- [x] Process is organised with groups (dashed boxes)
- [x] Straight lines are preferred where possible
- [x] Subprocesses are forbidden
- [x] Text mode is preferred over Expressions in expressions, e.g. instead of *$"This is {#var.error}"* use *This is {{#var.error}}*
- [x] Process metadata file is present and content is fine (version number and name)
- [x] Process export file is present (process.json)
- [x] Process description file is present (all sections filled in)
- [x] Process description has a SVG screenshot of the process
- [x] Tempalte files are going to the correct folder

## Summary by CodeRabbit

- **New Features**
  - Introduced a template for validating HTTP request query parameters and executing paginated searches in a Microsoft SQL database. This enhances the ability to perform efficient and user-defined data retrieval.

- **Documentation**
  - Added detailed descriptions and usage notes for the new template, including error handling and limitations, ensuring clarity on implementing paginated searches from a Microsoft SQL database.

### CODE REVIEW

**Review by jannejjj — DISMISSED** [review]
No comments for this, everything seems good to me!

**Review by jannejjj — COMMENTED** [review]
I've already tested this template before, so all that's left is to add the double newlines in the description, then this is done!

**Comment by FrendsSarlinS** [comment]
Double newlines are now included and this should be good to go!

**Review by jannejjj — APPROVED** [review]
Yep, this is now done.

**Pull request merged**
