### PR TITLE
Shopify to HubSpot - Orders

### LINKED ISSUE #124: Shopify orders sync to HubSpot
Sync order data from Shopify to HubSpot

---
Parameters:
- Shopify creds
- HubSpot creds

### PR DESCRIPTION
**Pull request by FrendsSarlinS**
Closes #124 

Checklist for review:
- [x] Process name is fine, uses normal casing and descriptive
- [x] Process description is fine, uses normal casing, dots and is descriptive
  - [x] Element names use normal casing, no unneeded capital letters.
- [x] Correct casing used for formats and terms, e.g. CSV, FTP, JSON, Avro
  - [x] Element names do not contain dots
  - [x] Comments / note element text are in good language and end with dots.
- [x] Template parameters checked
  - [x] Parameter descriptions are good and end with dots.
  - [x] Sensitive parameters are marked as secrets
- [x] "Turn off logging" switch is on for any task that has sensitive data as output
- [x] End "balls" like error throws and return statements have titles (double-click) and reasonable information.
  - [x] Results have good summaries, preferably with statistics of some sort like "processed X files"
  - [x] Errors have some error info, usually from task (e.g. some ErrorMessage property contains additional error info)
- [x] Process is organised with groups (dashed boxes)
- [x] Straight lines are preferred where possible
- [x] Subprocesses are forbidden
- [x] Text mode is preferred over Expressions in expressions, e.g. instead of *$"This is {#var.error}"* use *This is {{#var.error}}*
- [x] Process metadata file is present and content is fine (version number and name)
- [x] Process export file is present (process.json)
- [x] Process description file is present (all sections filled in)
- [x] Process description has a SVG screenshot of the process
- [x] Tempalte files are going to the correct folder

## Summary by CodeRabbit

- **New Features**
  - Introduced a template for exporting Shopify orders and line items to HubSpot as deals, ensuring seamless data transfer between platforms.
  - Enhanced integration with the addition of conditional logic for order and line item processing.
  - Included error handling mechanisms to maintain data integrity during synchronization.

- **Documentation**
  - Added detailed descriptions and metadata for the new Shopify to HubSpot order export template.

### CODE REVIEW

**Comment by jannejjj** [comment]
Were you planning to adjust this template to use the while-loop instead of for to prevent partial orders being inserted into HubSpot? 😄

In any case, currently in your for-each loop, if inserting a line item is not successful, there's a return saying "[...] take the next order", but in that case the foreach will just move to the next line. So if you were planning to change to the while-loop, ignore that, but if not, then change the wording at least! 👌

**Comment by FrendsSarlinS** [comment]
> Were you planning to adjust this template to use the while-loop instead of for to prevent partial orders being inserted into HubSpot? 😄
> 
> In any case, currently in your for-each loop, if inserting a line item is not successful, there's a return saying "[...] take the next order", but in that case the foreach will just move to the next line. So if you were planning to change to the while-loop, ignore that, but if not, then change the wording at least! 👌

Oh, thanks for spotting that return! Yes, I'm adjusting this template to use the while-loop this week, so it's still a bit WIP. I'll post a comment here when it's done!

**Comment by FrendsSarlinS** [comment]
Took me a while, but the loop is now redesigned. The template is now ready for review!

**Review by jannejjj — CHANGES_REQUESTED** [review]
Other than the two comments I left in the description, I noticed 2 things:

- in the "stop processing current order" return, after the task where we delete a partially successful order, the expression is `#var.linesProcessingFinished == true`, when it should only have one equals-sign (i.e., it should set linesProcessingFinished to true instead of comparing it with true) 😄

- The template sets the currency of each individual line correctly, but doesn't set a currency for the whole deal, resulting in (at least on our test instance) the deal being in USD and the lines in EUR, which causes some warnings:
image
It looks like the currency of each order from Shopify is available in the fetched data, so we should see if it's possible to set it for the deal on HubSpot as well. 😄

**Comment by FrendsSarlinS** [comment]
> Other than the two comments I left in the description, I noticed 2 things:
> 
> * in the "stop processing current order" return, after the task where we delete a partially successful order, the expression is `#var.linesProcessingFinished == true`, when it should only have one equals-sign (i.e., it should set linesProcessingFinished to true instead of comparing it with true) 😄
> * The template sets the currency of each individual line correctly, but doesn't set a currency for the whole deal, resulting in (at least on our test instance) the deal being in USD and the lines in EUR, which causes some warnings:
>   It looks like the currency of each order from Shopify is available in the fetched data, so we should see if it's possible to set it for the deal on HubSpot as well. 😄

Thanks for pointing that out, the == missed my radar totally in that part!
As for the currency issue, HubSpot deals' object handles currencies a bit differently from Shopify or the line_items object. In Shopify, the currency code is available as a string, like "EUR" or "USD". I tried applying that to a deal, like it works with the line_items object, but order creation fails because of that - maybe because of a syntax mismatch. Because of that, I've left it empty for now.

**Comment by jannejjj** [comment]
After reading [this page](https://knowledge.hubspot.com/object-settings/add-and-edit-your-account-currencies), the problem is probably that the currency we're trying to add to the orders (EUR) is not added to Hubspot, so it uses the default one.

That probably means that it would be fine just to modify the description to mention that the currency of the deals will be set to the default currency of Hubspot, and to remove the handling for setting a currency for the specific lines in the deals as well. (i assume that the lines will also default to using the default currency on hubspot if no currency is specified)

**Review by jannejjj — APPROVED** [review]
The template has now been changed to use the default currency from HubSpot, which makes sense. It has also been mentioned in the description, so all's good!

**Pull request merged**
