### PR TITLE
Zoho CRM to JSON - Contacts

### LINKED ISSUE #170: Zoho CRM to JSON - Customers

### PR DESCRIPTION
**Pull request by FrendsSarlinS**
Closes #170 

Checklist for review:
- [x] Process name is fine, uses normal casing and descriptive
  - [x] If applicable, the process name follows the naming convention "{source/format} to {destination/format} - {object}"
- [x] Process description is fine, uses normal casing, dots and is descriptive
  - [x] Element names use normal casing, no unneeded capital letters
- [x] Correct casing used for formats and terms, e.g. CSV, FTP, JSON, Avro
  - [x] Element names do not contain dots
  - [x] Comments / note element text are in good language and end with dots
- [x] Template parameters checked
  - [x] Parameter follows the CamelCase naming convention, abbreviations included, e.g. ConnectionString, BaseUrl, ApiKey
  - [x] Parameter descriptions are good and end with dots
  - [x] Sensitive parameters are marked as secrets
- [x] "Turn off logging" switch is on for any task that has sensitive data as output, e.g. tokens in the header.
- [x] Process end points like error throws and return statements have titles (double-click) and reasonable information.
  - [x] Results have good summaries, preferably with statistics of some sort like "processed X files"
  - [x] Errors have some error info, usually from task (e.g. some ErrorMessage property contains additional error info)
  - [x] Errors are pointed downwards from their respective source, e.g. an exclusive decision
- [x] Process is organised with groups (dashed boxes)
- [x] Straight lines are preferred where possible
- [x] Subprocesses are forbidden
- [x] Text mode is preferred over Expressions in expressions, e.g. instead of *$"This is {#var.error}"* use *This is {{#var.error}}*
- [x] Process metadata file is present and content is fine (version number and name)
- [x] Process export file is present (process.json)
- [x] Process description file is present (all sections filled in)
- [x] Process description has a SVG screenshot of the process
- [x] Template files are going to the correct folder
- [x] Markdown paragraphs are separated with two newlines, so there is a blank line inbetween two paragraphs
- [x] If some system is integrated using e.g. a HTTP task (meaning we do not use a native connector for the system), then the system should be mentioned in additional systems used in metadata.json
- [x] If the template is handling some sample JSON data - make sure that the sample data is included in the long description (just one-two elements is enough)
- [x] If the template is assuming that there is a database table ready for data insertion / updates - include the table structure in the long description as a `CREATE TABLE` scipt.

## Summary by CodeRabbit

- **New Features**
  - Introduced a template for exporting contact data from Zoho CRM as a JSON file, enhancing data retrieval and storage capabilities.
  - Added a structured process template that includes error handling mechanisms for effective extraction and storage of contact data.

- **Documentation**
  - Enhanced documentation for the new template, outlining prerequisites, implementation steps, and error management processes.

### CODE REVIEW

**Comment by FrendsSarlinS** [comment]
> Nice work with handling the pagination and everything! A few comments:
> 
> * Check the result of the throw inside the loop: since it's in text mode, it doesn't give the \n symbols as new lines. Would just giving the whole .Body be ok? All in all, it's nice how much information is passed in the error message.
> * Also, should the token task also have an error check after it?
> * Process variable InFilePath: I think the name should be either OutFilePath or TargetFilePath as it's used for export.
> * Check the naming of the dashed boxes: "Writing to the local fileshare" & would something like "Retrieving Zoho CRM contacts" be more in line with the other one?

Thanks for great insights! I took notes of all of them and pushed new changes in according to your review.

**Comment by charlotta-frends** [comment]
You're right about the .Body, your solution is indeed nicer!

Everything else is ok, but the added error check for the token task returns the status code 200 even if the request fails because of invalid credentials etc, so the check should include something like if Body.error is null, I think.

**Comment by jannejjj** [comment]
If there are more than one page in the response from the Zoho API, the output JSON will have `][` in the points where a new page begins, since the `data` in the api response is an array:

image

I noticed this issue when working on my own Zoho to JSON export template, and wanted to check if you'd noticed it too. I fixed it with simply passing `#var.products.Replace("][", ",")` as the content for the write task. That results in something like this, which is valid JSON (tested by giving it as input for the JSON to Zoho import template):

image

The page size can be changed by including `&per_page=(desired page size)` at the end of the HTTP request to the Zoho api. 😄

**Comment by FrendsSarlinS** [comment]
Great find Janne! Thanks a lot, added that in to this template!

**Comment by jannejjj** [comment]
The issue I mentioned has been addressed, @charlotta-frends can continue reviewing the things you discussed previously. 😄

**Review by charlotta-frends — APPROVED** [review]
All changes ok, ready to be merged!

**Pull request merged**
