### PR TITLE
Local Excel to Microsoft SQL

### LINKED ISSUE #125: Retrieve Excel data and save to database
1. Read Excel files from local disk or SFTP
2. Parse them and save to a database table
---
Parameters
- Source file information
- Database information
- Target table name

### PR DESCRIPTION
**Pull request by FrendsSarlinS**
Closes #125 .

Checklist for review:
- [x] Process name is fine, uses normal casing and descriptive
  - [x] If applicable, the process name follows the naming convention "{source/format} to {destination/format} - {object}"
- [x] Process description is fine, uses normal casing, dots and is descriptive
  - [x] Element names use normal casing, no unneeded capital letters
- [x] Correct casing used for formats and terms, e.g. CSV, FTP, JSON, Avro
  - [x] Element names do not contain dots
  - [x] Comments / note element text are in good language and end with dots
- [x] Template parameters checked
  - [x] Parameter follows the CamelCase naming convention, abbreviations included, e.g. ConnectionString, BaseUrl, ApiKey
  - [x] Parameter descriptions are good and end with dots
  - [x] Sensitive parameters are marked as secrets
- [x] "Turn off logging" switch is on for any task that has sensitive data as output, e.g. tokens in the header.
- [x] Process end points like error throws and return statements have titles (double-click) and reasonable information.
  - [x] Results have good summaries, preferably with statistics of some sort like "processed X files"
  - [x] Errors have some error info, usually from task (e.g. some ErrorMessage property contains additional error info)
  - [x] Errors are pointed downwards from their respective source, e.g. an exclusive decision
- [x] Process is organised with groups (dashed boxes)
- [x] Straight lines are preferred where possible
- [x] Subprocesses are forbidden
- [x] Text mode is preferred over Expressions in expressions, e.g. instead of *$"This is {#var.error}"* use *This is {{#var.error}}*
- [x] Process metadata file is present and content is fine (version number and name)
- [x] Process export file is present (process.json)
- [x] Process description file is present (all sections filled in)
- [x] Process description has a SVG screenshot of the process
- [x] Template files are going to the correct folder

## Summary by CodeRabbit

- **New Features**
  - Introduced a template to parse local Excel files and import them into a Microsoft SQL database table. It includes detailed instructions, prerequisites, implementation specifics, usage notes, and error handling procedures.

### CODE REVIEW

**Review by charlotta-frends — APPROVED** [review]
Checks all boxes, looks fine to me!

**Comment by charlotta-frends** [comment]
With the new additions to the checklist, I was wondering if the long description should include an example CREATE TABLE script - then again, it depends so heavily on the Excel file's contents, that it's maybe not necessary (?), as it would need to be a very generic one.

Without the script, maybe the SQL table and/or file content parts in prerequisites could be elaborated a little more, e.g., the Excel column contents need to match the SQL data types to be transferred successfully, there needs to be as many columns in both, etc.?

**Comment by FrendsSarlinS** [comment]
> With the new additions to the checklist, I was wondering if the long description should include an example CREATE TABLE script - then again, it depends so heavily on the Excel file's contents, that it's maybe not necessary (?), as it would need to be a very generic one.
> 
> Without the script, maybe the SQL table and/or file content parts in prerequisites could be elaborated a little more, e.g., the Excel column contents need to match the SQL data types to be transferred successfully, there needs to be as many columns in both, etc.?

That's a good point! I'm thinking of adding both SQL table example and corresponding Excel example for clarity.

**Comment by charlotta-frends** [comment]
With the changes to the description, this is all ready and done!

**Pull request merged**
